version: '3.9'

services:
  spring-boot-app:
    image: openjdk:17
    container_name: spring-boot-app
    working_dir: /app
    volumes:
      - ./target/auth-0.0.1-SNAPSHOT.jar:/app/auth-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auths
      - SPRING_DATASOURCE_USERNAME=auth
      - SPRING_DATASOURCE_PASSWORD=auth
    depends_on:
      - db
    command: ["java", "-jar", "auth-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auths
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./looping/auth.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
